micronaut:
  application:
    name: demo

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/testdb`}
    username: ${JDBC_USER:test}
    password: ${JDBC_PASSWORD:test}
    dialect: POSTGRES
    auto-commit: true
    schema-generate: CREATE_DROP
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    entity-scan:
      packages: com.example.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
